version: '3.1'

services:
  apidocker:
    image: manologcode/apidocker
    restart: always
    container_name: apidocker
    ports:
      - "8888:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  startpage:
    image: nginx:alpine
    restart: always
    container_name: startpage
    ports:
      - 80:80
    volumes:
      - ./startpage:/usr/share/nginx/html:ro
